[package]
name = "bevy_control"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"

[[example]]
name = "camera_2d"
path = "examples/camera_2d.rs"

[[example]]
name = "camera_3d"
path = "examples/camera_3d.rs"
