[package]
name = "bevy_control"
version = "0.2.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"

[[example]]
name = "camera_anchors"
path = "examples/camera_anchors.rs"

[[example]]
name = "camera_target"
path = "examples/camera_target.rs"
